const kits = [
  {
    name: 'Just Blaze',
    sounds: {
      1: './sounds/justBlaze/JustBlaze-989kick.wav',
      2: './sounds/justBlaze/JustBlaze-blueprintKick10.wav',
      3: './sounds/justBlaze/JustBlaze-CFIRM.wav',
      4: './sounds/justBlaze/JustBlaze-dlz19.wav',
      5: './sounds/justBlaze/JustBlaze-dlz28.wav',
      6: './sounds/justBlaze/JustBlaze-fullKick.wav',
      7: './sounds/justBlaze/JustBlaze-hat3.wav',
      8: './sounds/justBlaze/JustBlaze-hat6.wav',
      9: './sounds/justBlaze/JustBlaze-hatkick4.wav',
      10: './sounds/justBlaze/JustBlaze-loosenar.wav',
      11: './sounds/justBlaze/JustBlaze-openHat2.wav',
      12: './sounds/justBlaze/JustBlaze-rim1.wav',
      13: './sounds/justBlaze/JustBlaze-sound10.wav',
      14: './sounds/justBlaze/JustBlaze-tambsnare.wav',
      15: './sounds/justBlaze/JustBlaze-Trin_Snare.wav',
      16: './sounds/justBlaze/JustBlaze-verbSnapRim.wav',
    },
    youtubeUrl: 'https://www.youtube.com/embed/wQ7rkIppxPM',
    soundcloudUrl: 'https://soundcloud.com/just-blaze',
  },
  {
    name: 'Metro Boomin',
    sounds: {
      1: './sounds/metroBoomin/MetroHat1.wav',
      2: './sounds/metroBoomin/rimshot1-modify.wav',
      3: './sounds/metroBoomin/808-3.wav',
      4: './sounds/metroBoomin/808-4-modify.wav',
      5: './sounds/metroBoomin/808-5.wav',
      6: './sounds/metroBoomin/clap1-modify.wav',
      7: './sounds/metroBoomin/clap2-modify.wav',
      8: './sounds/metroBoomin/clap3-modify.wav',
      9: './sounds/metroBoomin/clap4-modify.wav',
      10: './sounds/metroBoomin/crash1-modify.wav',
      11: './sounds/metroBoomin/hat1-modify.wav',
      12: './sounds/metroBoomin/hat2-modify.wav',
      13: './sounds/metroBoomin/hat3-modify.wav',
      14: './sounds/metroBoomin/hat4-modify.wav',
      15: './sounds/metroBoomin/kick1.wav',
      16: './sounds/metroBoomin/kick2.wav',
    },
    youtubeUrl: 'https://www.youtube.com/embed/Av4NhUWQ-24',
    soundcloudUrl: 'https://soundcloud.com/metroboomin'
  },
  {
    name: 'Boi-1da',
    sounds: {
      1: './sounds/boi-1da/boi1da - Ahh.wav',
      2: './sounds/boi-1da/boi1da - AuntyKick2.wav',
      3: './sounds/boi-1da/boi1da - batmanSnare.wav',
      4: './sounds/boi-1da/boi1da - beautifulHat.wav',
      5: './sounds/boi-1da/boi1da - clap.wav',
      6: './sounds/boi-1da/boi1da - hat3.wav',
      7: './sounds/boi-1da/boi1da - Ho.wav',
      8: './sounds/boi-1da/boi1da - NightDuoKick.wav',
      9: './sounds/boi-1da/boi1da - NightKcik.wav',
      10: './sounds/boi-1da/boi1da - openHat.wav',
      11: './sounds/boi-1da/boi1da - quadSnare.wav',
      12: './sounds/boi-1da/boi1da - shaker.wav',
      13: './sounds/boi-1da/boi1da - snare.wav',
      14: './sounds/boi-1da/boi1da - tink.wav',
      15: './sounds/boi-1da/boi1da - trioSnare.wav',
      16: './sounds/boi-1da/boi1da - Yeah.wav',
    },
    youtubeUrl: 'https://www.youtube.com/embed/Z9Fv3_1kgRY',
    soundcloudUrl: 'https://soundcloud.com/boi1damusic',
  },

]

export default kits;
